export const AUTH_LOAD = 'AUTH_LOAD'
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS'
export const AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL'

export const AUTH_SAVE = 'AUTH_SAVE'
export const AUTH_SAVE_SUCCESS = 'AUTH_SAVE_SUCCESS'
export const AUTH_SAVE_FAIL = 'AUTH_SAVE_FAIL'

export const EMAIL_VERIFICATION = 'EMAIL_VERIFICATION'
export const EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS'
export const EMAIL_VERIFICATION_FAIL = 'EMAIL_VERIFICATION_FAIL'

export const EMAIL_VERIFICATION_RESEND = 'EMAIL_VERIFICATION_RESEND'
export const EMAIL_VERIFICATION_RESEND_SUCCESS = 'EMAIL_VERIFICATION_RESEND_SUCCESS'
export const EMAIL_VERIFICATION_RESEND_FAIL = 'EMAIL_VERIFICATION_RESEND_FAIL'

export const LOAD_CONFIG = 'LOAD_CONFIG'
export const LOAD_CONFIG_SUCCESS = 'LOAD_CONFIG_SUCCESS'
export const LOAD_CONFIG_FAIL = 'LOAD_CONFIG_FAIL'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const UPDATE_BALANCE = 'UPDATE_BALANCE'

export const RELOADING = 'RELOADING'
export const RELOAD_SUCCESS = 'RELOAD_SUCCESS'
export const RELOAD_FAIL = 'RELOAD_FAIL'

export const DESTROY = 'DESTROY'

export const PAYMENT_JSON_LOADING = 'PAYMENT_JSON_LOADING'
export const PAYMENT_JSON_SUCCESS = 'PAYMENT_JSON_SUCCESS'
export const PAYMENT_JSON_FAIL = 'PAYMENT_JSON_FAIL'
export const PAYMENT_JSON_SHOW = 'PAYMENT_JSON_SHOW'
export const PAYMENT_JSON_HIDE = 'PAYMENT_JSON_HIDE'

export const WS_PAYMENT = 'WS_PAYMENT'

export const SEND = 'SEND'
export const SEND_SUCCESS = 'SEND_SUCCESS'
export const SEND_FAIL = 'SEND_FAIL'
export const SEND_RESET = 'SEND_RESET'

export const DESTINATION_CHANGE = 'DESTINATION_CHANGE'
export const DESTINATION_CHANGE_SUCCESS = 'DESTINATION_CHANGE_SUCCESS'
export const DESTINATION_CHANGE_FAIL = 'DESTINATION_CHANGE_FAIL'

export const REQUEST_QUOTE = 'REQUEST_QUOTE'
export const REQUEST_QUOTE_SUCCESS = 'REQUEST_QUOTE_SUCCESS'
export const REQUEST_QUOTE_FAIL = 'REQUEST_QUOTE_FAIL'

export const LOAD_TRANSFERS = 'LOAD_TRANSFERS'
export const LOAD_TRANSFERS_SUCCESS = 'LOAD_TRANSFERS_SUCCESS'
export const LOAD_TRANSFERS_FAIL = 'LOAD_TRANSFERS_FAIL'
